# ------------------------------------------------------------------------------------------
# This is a workflow to build an bootable Armbian SD card image with a Linux kernel
# and appropriate boot images to setup the NAND on a Cubietruck (SUNXI A20 board)
# for:
#   - SUNXI NAND support within mainline kernel
#   - booting from NAND with mainline U-Boot
#   - have a NAND partition configured for an UBI filesystem
#
# ------------------------------------------------------------------------------------------
name: Build Armbian for Cubietruck

on:
  workflow_dispatch:
  #push:
  #  tags:
  #    - 'v[0-9]+.[0-9]+.[0-9]+'
  #    - 'v[0-9]+.[0-9]+.[0-9]+.[0-9]+'
  push:
    branches:
      - master
  #    - boards/cubietruck
  #schedule:
  #    - cron: 0 8 * * 5

jobs:
  job1_Build:
    name: Build U-Boot
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Environment
        run: |
          TOOLCHAIN_URL_VERSION=7.4-2019.02
          TOOLCHAIN_FILE_VERSION=7.4.1-2019.02
          TOOLCHAIN_TARGET=aarch64-linux-gnu
          TOOLCHAIN_HOST=x86_64
          TOOLCHAIN_FULL_NAME=gcc-linaro-${TOOLCHAIN_FILE_VERSION}-${TOOLCHAIN_HOST}_${TOOLCHAIN_TARGET}
          echo "TOOLCHAIN_URL_VERSION=${TOOLCHAIN_URL_VERSION}" >> $GITHUB_ENV
          echo "TOOLCHAIN_FILE_VERSION=${TOOLCHAIN_FILE_VERSION}" >> $GITHUB_ENV
          echo "TOOLCHAIN_TARGET=${TOOLCHAIN_TARGET}" >> $GITHUB_ENV
          echo "TOOLCHAIN_HOST=${TOOLCHAIN_HOST}" >> $GITHUB_ENV
          echo "TOOLCHAIN_FULL_NAME=${TOOLCHAIN_FULL_NAME}" >> $GITHUB_ENV

      - name: Log Environment
        run: |
          echo "  TOOLCHAIN_URL_VERSION:  ${TOOLCHAIN_URL_VERSION}"
          echo "  TOOLCHAIN_FILE_VERSION: ${TOOLCHAIN_FILE_VERSION}"
          echo "  TOOLCHAIN_TARGET:       ${TOOLCHAIN_TARGET}"
          echo "  TOOLCHAIN_HOST:         ${TOOLCHAIN_HOST}"
          echo "  TOOLCHAIN_FULL_NAME:    ${TOOLCHAIN_FULL_NAME}"

      - name: Prepare folders
        run: |
          mkdir -p cache/{toolchains,tmp}
          mkdir -p output

      - name: Install Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: lzop build-essential gcc bc libncurses5-dev libc6-i386 lib32stdc++6 zlib1g
          # Cache version:
          version: 1.0

      - name: Install Toolchain
        run: |
          curl -L -o cache/toolchains/${{ env.TOOLCHAIN_FULL_NAME }}.tar.xz https://releases.linaro.org/components/toolchain/binaries/${{ env.TOOLCHAIN_URL_VERSION }}/${{ env.TOOLCHAIN_TARGET }}/${{ env.TOOLCHAIN_FULL_NAME }}.tar.xz
          tar -xvf cache/toolchains/${{ env.TOOLCHAIN_FULL_NAME }}.tar.xz -C cache/toolchains/
          rm --verbose -rf cache/toolchains/${{ env.TOOLCHAIN_FULL_NAME }}.tar.xz

      - name: Checkout M1 U-Boot
        run: |
          git clone https://github.com/hardkernel/u-boot.git -b odroidm1-v2017.09
