# ------------------------------------------------------------------------------------------
# This is a workflow to build U-Boot for Odroid M1.
# According to: https://wiki.odroid.com/odroid-m1/software/building_u-boot
#
# ------------------------------------------------------------------------------------------
name: Build U-Boot for Odroid M1

on:
  workflow_dispatch:
  #push:
  #  tags:
  #    - 'v[0-9]+.[0-9]+.[0-9]+'
  #    - 'v[0-9]+.[0-9]+.[0-9]+.[0-9]+'
  push:
    branches:
      - master
  #schedule:
  #    - cron: 0 8 * * 5

jobs:
  job1_Build:
    name: Build U-Boot
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Environment
        run: |
          TOOLCHAIN_URL_VERSION=7.4-2019.02
          TOOLCHAIN_FILE_VERSION=7.4.1-2019.02
          TOOLCHAIN_TARGET=aarch64-linux-gnu
          TOOLCHAIN_HOST=x86_64
          TOOLCHAIN_FULL_NAME=gcc-linaro-${TOOLCHAIN_FILE_VERSION}-${TOOLCHAIN_HOST}_${TOOLCHAIN_TARGET}
          echo "TOOLCHAIN_URL_VERSION=${TOOLCHAIN_URL_VERSION}" >> $GITHUB_ENV
          echo "TOOLCHAIN_FILE_VERSION=${TOOLCHAIN_FILE_VERSION}" >> $GITHUB_ENV
          echo "TOOLCHAIN_TARGET=${TOOLCHAIN_TARGET}" >> $GITHUB_ENV
          echo "TOOLCHAIN_HOST=${TOOLCHAIN_HOST}" >> $GITHUB_ENV
          echo "TOOLCHAIN_FULL_NAME=${TOOLCHAIN_FULL_NAME}" >> $GITHUB_ENV

      - name: Log Environment
        run: |
          echo "  TOOLCHAIN_URL_VERSION:  ${TOOLCHAIN_URL_VERSION}"
          echo "  TOOLCHAIN_FILE_VERSION: ${TOOLCHAIN_FILE_VERSION}"
          echo "  TOOLCHAIN_TARGET:       ${TOOLCHAIN_TARGET}"
          echo "  TOOLCHAIN_HOST:         ${TOOLCHAIN_HOST}"
          echo "  TOOLCHAIN_FULL_NAME:    ${TOOLCHAIN_FULL_NAME}"

      - name: Prepare folders
        run: |
          mkdir -p cache/{toolchains,tmp}
          mkdir -p output

      - name: Install Packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: lzop build-essential gcc bc libncurses5-dev libc6-i386 lib32stdc++6 zlib1g device-tree-compiler python2
          # Cache version:
          version: 1.0

      - name: Install Toolchain
        run: |
          curl -L -o cache/toolchains/${{ env.TOOLCHAIN_FULL_NAME }}.tar.xz https://releases.linaro.org/components/toolchain/binaries/${{ env.TOOLCHAIN_URL_VERSION }}/${{ env.TOOLCHAIN_TARGET }}/${{ env.TOOLCHAIN_FULL_NAME }}.tar.xz
          tar -xvf cache/toolchains/${{ env.TOOLCHAIN_FULL_NAME }}.tar.xz -C cache/toolchains/
          rm --verbose -rf cache/toolchains/${{ env.TOOLCHAIN_FULL_NAME }}.tar.xz

      - name: Checkout M1 U-Boot
        run: |
          # git clone https://github.com/hardkernel/u-boot.git -b odroidm1-v2017.09
          git clone --progress --verbose https://github.com/MHARMBIAN/rklinux_u-boot.git -b odroidm1-v2017.09 u-boot

      - name: Compile U-Boot
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=${{ env.TOOLCHAIN_TARGET }}-
          export PATH=$(pwd)/cache/toolchains/${{ env.TOOLCHAIN_FULL_NAME }}/bin:$PATH
          cd u-boot
          git submodule init
          git submodule update
          ./make.sh odroid_rk3568



